import Vue from "vue";
import { Button } from "element-ui";
import { Header } from "element-ui";
import { Container } from "element-ui";
import { Main } from "element-ui";
import { Menu } from "element-ui";
import { Submenu } from "element-ui";
import { MenuItem } from "element-ui";
import { Form } from "element-ui";
import { FormItem } from "element-ui";
import { Input } from "element-ui";
import { Message } from "element-ui";
import { Upload } from "element-ui";
import { Select } from "element-ui";
import { Option } from "element-ui";
import { DatePicker } from "element-ui";
import { Carousel } from "element-ui";
import { CarouselItem } from "element-ui";
import { Image } from "element-ui";
import { Avatar } from "element-ui";
import { Card } from "element-ui";

Vue.prototype.$message = Message;

Vue.use(Button);
Vue.use(Header);
Vue.use(Container);
Vue.use(Main);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Upload);
Vue.use(Select);
Vue.use(Option);
Vue.use(DatePicker);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Image);
Vue.use(Avatar);
Vue.use(Card);

